name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Cache nix store
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}

    - name: Check teal files
      run: |
        nix-shell --pure --run "make ensure"

    - name: Run tests
      run: |
        nix-shell --pure --run "make test"
